//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace equilibrio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloCarro
    {
        public int codigo { get; set; }
        public int cantidad { get; set; }
        public int fk_articulo { get; set; }
        public int fk_carro { get; set; }
    
        public virtual Artículo Artículo { get; set; }
        public virtual CarroCompras CarroCompras { get; set; }
    }
}
