//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace equilibrio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseña
    {
        public int codigo { get; set; }
        public int puntuacion { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha { get; set; }
        public int fk_sede { get; set; }
        public Nullable<int> fk_usuario { get; set; }
    
        public virtual Sede Sede { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
